# Font families.
# font_family      JetBrainsMono Nerd Font
# font_family      VictorMono Nerd Font Mono
# font_family      FiraCode Mono Medium
#

# font_family      FiraCode Nerd Font Mono
#
# italic_font      FiraCode Nerd Mono Medium Italic
# bold_font        FiraCode Nerd Mono Bold
# bold_italic_font FiraCode Nerd Mono Bold Italic

# font_family      Hack Nerd Font Mono
#
# italic_font      Hack Nerd Font Mono Italic
# bold_font        Hack Nerd Font Mono Bold
# bold_italic_font Hack Nerd Font Mono Bold Italic

#

# Fira Code
#     Fira Code Bold
#     Fira Code Light
#     Fira Code Medium
#     Fira Code Regular
#     Fira Code Retina
#     Fira Code SemiBold
#
# FiraCode Nerd Font Mono
#     FiraCode Nerd Font Mono Bold
#     FiraCode Nerd Font Mono Light
#     FiraCode Nerd Font Mono Medium
#     FiraCode Nerd Font Mono Regular
#     FiraCode Nerd Font Mono Retina
#     FiraCode Nerd Font Mono SemiBold
#
#

font_family      Fira Code

italic_font      Fira Code Light
bold_font        Fira Code Bold
bold_italic_font Fira Code SemiBold

# italic_font      auto
# bold_font        auto
# bold_italic_font auto

# italic_font      VictorMono Nerd Font Mono Medium Italic
# bold_font        VictorMono Nerd Font Mono Bold
# bold_italic_font VictorMono Nerd Font Mono Bold Italic
# # Font size in pts.
font_size 11.0
# font_features ss01
# Change the size of each character cell kitty renders.
# adjust_line_height 0
# adjust_column_width 0
# less sapace and more space for text
# adjust_line_height  85%
# adjust_column_width 96%
# Map the specified unicode codepoints to a particular font.
# symbol_map U+E0A0-U+E0A2,U+E0B0-U+E0B3 PowerlineSymbols
# symbol_map U+E0A0-U+E0A3,U+E0C0-U+E0C7 PowerlineSymbols

# Whether or not show multi-character ligatures.
# disable_ligatures cursor

# symbol_map U+ea60-U+ebd1 Fira Code
# symbol_map codepoints Fira Code

disable_ligatures never

# Change the sizes of the lines in pts used for the box drawing.
# box_drawing_scale 0.001, 1, 1.5, 2

