kitty_mod cmd+shift

map kitty_mod+c copy_to_clipboard
map kitty_mod+v paste_from_clipboard
map kitty_mod+s paste_from_selection
# map cmd+q     close_window

# map kitty_mod+left   resize_window narrower
# map kitty_mod+right  resize_window wider
# map kitty_mod+up     resize_window taller
# map kitty_mod+down   resize_window shorter

map cmd+t no_op
map cmd+H no_op
map cmd+J no_op
map cmd+K no_op
map cmd+L no_op

map cmd+h no_op
map cmd+j no_op
map cmd+k no_op
map cmd+l no_op
map cmd+r no_op

map cmd+, no_op
map cmd+. no_op

map cmd+w no_op

map kitty_mod+h no_op
map kitty_mod+j no_op
map kitty_mod+k no_op
map kitty_mod+l no_op

map cmd+n no_op
map cmd+1 no_op
map cmd+2 no_op
map cmd+3 no_op
map cmd+4 no_op
map cmd+5 no_op
map cmd+6 no_op
map cmd+7 no_op
map cmd+8 no_op
map cmd+9 no_op

map ctrl+tab no_op
map ctrl+shift+tab no_op

map kitty_mod+t no_op
map kitty_mod+h no_op
map kitty_mod+j no_op
map kitty_mod+k no_op
map kitty_mod+l no_op
